### ISSUE TITLE
the code uploaded in the github and youtube video is not the same

### ISSUE THREAD

**Issue by vinayuppada** [Geek24YT/background-remover#1]
the defining of variable  the a is wrong  in the downloadfile() function you shouldn't define the variable a because a refers to the anchor tag. so please change the code reupload the code .

**Comment by vinayuppada** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    

    <div class="container mt-4">
        <div class="row mt-4">
        <div class="col-md-12 card mt-4">
        <form>
        <div class="form-group">
        <label for="fileInput">Select a File: </label> 
        <input id="fileInput" class="form-control" 
        type="file">
        </div>
        <input class="btn btn-primary m-1" 
        type="button"  onclick="submitHandler()"
        value="Upload">
        </form>

        <button class="btn btn-warning"
         onclick="downloadFile()">
         Download
        </button>
     
         </div>
        </div>
        </div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
    let imageURL;

    function submitHandler(){
       
const fileInput = document.getElementById('fileInput');
        //console.log(fileInput.files);
        const image = fileInput.files[0];

        // Multipart file
        const formData = new FormData();
        formData.append('image_file', image);
        formData.append('size', 'auto');

        const apiKey = 'uB1ntQx4m2L9dSi8zcQcY8Zd';

        fetch('https://api.remove.bg/v1.0/removebg',{
            method:'POST',
            headers: {
            'X-Api-Key': apiKey
         },
         body: formData
        })
        .then(function(reponse){
                return reponse.blob()
        })
        .then(function(blob){
                console.log(blob);
                const url = URL.createObjectURL(blob);
                imageURL = url;
                const img = document.createElement('img');
                img.src = url;
                document.body.appendChild(img);
        })
        .catch();

        console.log("click");
    }

   function downloadFile(){
    var ae = document.createElement('a'); //<a></a>
        ae.href = imageURL;
        ae.download = 'naciasv.png';
        document.body.appendChild(ae);

        ae.click();

        document.body.removeChild(a);
   }
</script>


</body>
</html>

**Comment by Geek24YT** [comment]
Hi, [vinayuppada](https://github.com/vinayuppada) I have updated the variable name now. Though its absolutely fine to give your variable name - "a" in shorter codebase, but yeah appropriate naming is always good practice thanks for pointing this out.
Cheers!
